default_stages: [commit]
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      args: [
        --line-length=100, 
      ]
      exclude: ^(venv/|docs/)
      types: ['python']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
          --line-length=100,
          --profile=black,
          --atomic
        ]
